apiVersion: v1
kind: Service
metadata:
  name: nginx01-svc
  namespace: argocd-test
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: http